### ISSUE TITLE
getObservables called whether triggerProps null or not matching.

### ISSUE THREAD

**Issue by dungnguyen10989** [Nozbe/withObservables#107]
I connected my Component, I only triggered a route (react-navigation props) change, but when I dispatch an action to add a record to the *POST* table then *getObservables* still calls to generate a new props to my Component ?
```
export default withDatabase(
  withObservables(['route'], (props: Props) => ({
    data: props.database.collections
      .get<DtoPost>(TABLES.POST)
      .query()
      .observe(),
  }))(ListPost),
);
```

**Comment by radex** [comment]
I'm pretty sure that `route` is an object that's regenerated on every change to navigation. A change in identity will cause a re-render, which is standard behavior in React
