### ISSUE TITLE
withObservables vs React Hooks

### ISSUE THREAD

**Issue by sidferreira** [Nozbe/withObservables#111]
I've been trying to use `withObservables`, `Ramda.pipe`, and `Typescript`. 
I recently found https://jasonwatmore.com/post/2020/04/21/react-hooks-rxjs-communicating-between-components-with-observable-subject and made me try the following:

```
const withIdToPost = (
    WrappedComponent: React.ComponentType<{ post: Post }>,
  ) => ({ id, ...props }: { id: string }) => {
    const [post, setPost] = React.useState<Post | undefined>();
  
    React.useEffect(() => {
      if (id) {
        const subscription = Post.query(Q.where('id', id))
          .observe()
          .subscribe((videos) => {
            if (videos.length > 0) {
                setPost(videos[0]);
            } else {
                Post.registerNotFound(id);
            }
          });
        return subscription.unsubscribe;
      }
    }, [id]);
  
    if (!post) {
      return null;
    }
  
    return <WrappedComponent post={post} {...props} />;
  };
```

I wonder if this approach would lose any behavior that `withObservable` offers (other than not being as generic as the first one)

**Comment by radex** [comment]
@sidferreira don't do it, you'll have a ton of unnecessary renders that withObservable avoids, and a lot of renders that render null - causing all sorts of ugly glitching.
