### ISSUE TITLE
Where is ObservablifyProps Typescript type defined?

### ISSUE THREAD

**Issue by bogdancochioras-clarisoft** [Nozbe/withObservables#71]
From the documentation it says there is this helper type `ObservablifyProps` but did not find any reference of it in the module and is not a Typescript default type.

**Comment by radex** [comment]
@jamieparkinson can you answer this question?

**Comment by jamieparkinson** [comment]
It's here https://github.com/Nozbe/withObservables/blob/master/index.d.ts#L18, you can import it like
```
import { ObservablifyProps } from "@nozbe/withObservables";
```

**Comment by bogdancochioras-clarisoft** [comment]
Hmm I don’t know how I missed it, maybe I had an older version locally or had a typo when searching for it, thanks!
