### ISSUE TITLE
Retrieve relation in the same HOC?

### ISSUE THREAD

**Issue by Jono20201** [Nozbe/withObservables#91]
Is there a way you can find an entity and also get its relations in the same HOC, or another way without having a HOC on top of a HOC?

Something like:

```javascript
const enhance = withObservables(['postId'], ({ postId, database }) => ({
  post: database.collections
      .get('posts')
      .find(postId),
  comments: <the above post>.comments.observe()
}));
```

**Comment by radex** [comment]
no, not possible. I recommend using a `compose()` function (available in most FP packages, and also `recompose`) to make chaining withObservables look nice and understandable.
